//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Models
{
    public partial class ContactForm
    {
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Reason { get; set; }
        public string Seen { get; set; }
        public string ContactDate { get; set; }
        public string Message { get; set; }
    }
}
